config/routes.rb
Catalog::Engine.routes.draw do
  resources :product_groups
  resources :products
end

app/models/catalog/application_record.rb
module Catalog
  class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
  end
end

app/models/catalog/product.rb
module Catalog
  class Product < ApplicationRecord
    belongs_to :product_group
  end
end

app/models/catalog/product_group.rb
module Catalog
  class ProductGroup < ApplicationRecord
    has_many :products
  end
end

app/controllers/catalog/application_controller.rb
module Catalog
  class ApplicationController < ActionController::Base
  end
end

app/controllers/catalog/product_groups_controller.rb
module Catalog
  class ProductGroupsController < ApplicationController
    before_action :set_product_group, only: %i[ show edit update destroy ]

    # GET /product_groups
    def index
      @product_groups = ProductGroup.all
    end

    # GET /product_groups/1
    def show
    end

    # GET /product_groups/new
    def new
      @product_group = ProductGroup.new
    end

    # GET /product_groups/1/edit
    def edit
    end

    # POST /product_groups
    def create
      @product_group = ProductGroup.new(product_group_params)

      if @product_group.save
        redirect_to @product_group, notice: "Product group was successfully created."
      else
        render :new, status: :unprocessable_entity
      end
    end

    # PATCH/PUT /product_groups/1
    def update
      if @product_group.update(product_group_params)
        redirect_to @product_group, notice: "Product group was successfully updated.", status: :see_other
      else
        render :edit, status: :unprocessable_entity
      end
    end

    # DELETE /product_groups/1
    def destroy
      @product_group.destroy!
      redirect_to product_groups_path, notice: "Product group was successfully destroyed.", status: :see_other
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_product_group
        @product_group = ProductGroup.find(params.expect(:id))
      end

      # Only allow a list of trusted parameters through.
      def product_group_params
        params.expect(product_group: [ :product_group_name ])
      end
  end
end

app/controllers/catalog/products_controller.rb
module Catalog
  class ProductsController < ApplicationController
    before_action :set_product, only: %i[ show edit update destroy ]

    # GET /products
    def index
      @products = Product.all
    end

    # GET /products/1
    def show
    end

    # GET /products/new
    def new
      @product = Product.new
    end

    # GET /products/1/edit
    def edit
    end

    # POST /products
    def create
      @product = Product.new(product_params)

      if @product.save
        redirect_to @product, notice: "Product was successfully created."
      else
        render :new, status: :unprocessable_entity
      end
    end

    # PATCH/PUT /products/1
    def update
      if @product.update(product_params)
        redirect_to @product, notice: "Product was successfully updated.", status: :see_other
      else
        render :edit, status: :unprocessable_entity
      end
    end

    # DELETE /products/1
    def destroy
      @product.destroy!
      redirect_to products_path, notice: "Product was successfully destroyed.", status: :see_other
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_product
        @product = Product.find(params.expect(:id))
      end

      # Only allow a list of trusted parameters through.
      def product_params
        params.expect(product: [ :name, :description, :price ])
      end
  end
end

app/helpers/catalog/application_helper.rb
module Catalog
  module ApplicationHelper
  end
end

app/helpers/catalog/product_groups_helper.rb
module Catalog
  module ProductGroupsHelper
  end
end

app/helpers/catalog/products_helper.rb
module Catalog
  module ProductsHelper
  end
end

app/views/catalog/product_groups/_form.html.erb
<%= form_with(model: product_group) do |form| %>
  <% if product_group.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(product_group.errors.count, "error") %> prohibited this product_group from being saved:</h2>

      <ul>
        <% product_group.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :product_group_name, style: "display: block" %>
    <%= form.text_field :product_group_name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/catalog/product_groups/_product_group.html.erb
<div id="<%= dom_id product_group %>">
  <p>
    <strong>Product group name:</strong>
    <%= product_group.product_group_name %>
  </p>

</div>

app/views/catalog/product_groups/edit.html.erb
<% content_for :title, "Editing product group" %>

<h1>Editing product group</h1>

<%= render "form", product_group: @product_group %>

<br>

<div>
  <%= link_to "Show this product group", @product_group %> |
  <%= link_to "Back to product groups", product_groups_path %>
</div>

app/views/catalog/product_groups/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Product groups" %>

<h1>Product groups</h1>

<div id="product_groups">
  <% @product_groups.each do |product_group| %>
    <%= render product_group %>
    <p>
      <%= link_to "Show this product group", product_group %>
    </p>
  <% end %>
</div>

<%= link_to "New product group", new_product_group_path %>

app/views/catalog/product_groups/new.html.erb
<% content_for :title, "New product group" %>

<h1>New product group</h1>

<%= render "form", product_group: @product_group %>

<br>

<div>
  <%= link_to "Back to product groups", product_groups_path %>
</div>

app/views/catalog/product_groups/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @product_group %>

<div>
  <%= link_to "Edit this product group", edit_product_group_path(@product_group) %> |
  <%= link_to "Back to product groups", product_groups_path %>

  <%= button_to "Destroy this product group", @product_group, method: :delete %>
</div>

app/views/catalog/products/_form.html.erb
<%= form_with(model: product) do |form| %>
  <% if product.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.textarea :description %>
  </div>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.number_field :price %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/catalog/products/_product.html.erb
<div id="<%= dom_id product %>">
  <p>
    <strong>Name:</strong>
    <%= product.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= product.description %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= product.price %>
  </p>

  <p>
    <strong>Product group:</strong>
    <%= product.product_group.product_group_name %>
  </p>


</div>

app/views/catalog/products/edit.html.erb
<% content_for :title, "Editing product" %>

<h1>Editing product</h1>

<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Show this product", @product %> |
  <%= link_to "Back to products", products_path %>
</div>

app/views/catalog/products/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Products" %>

<h1>Products</h1>

<div id="products">
  <% @products.each do |product| %>
    <%= render product %>
    <p>
      <%= link_to "Show this product", product %>
    </p>
  <% end %>
</div>

<%= link_to "New product", new_product_path %>

app/views/catalog/products/new.html.erb
<% content_for :title, "New product" %>

<h1>New product</h1>

<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Back to products", products_path %>
</div>

app/views/catalog/products/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @product %>

<div>
  <%= link_to "Edit this product", edit_product_path(@product) %> |
  <%= link_to "Back to products", products_path %>

  <%= button_to "Destroy this product", @product, method: :delete %>
</div>

app/views/layouts/catalog/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Catalog</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= yield :head %>

  <%= stylesheet_link_tag    "catalog/application", media: "all" %>
</head>
<body>

<%= yield %>

</body>
</html>